### ISSUE TITLE
may you share link to paper pls

### ISSUE THREAD

**Issue by Sandy4321** [GaelVaroquaux/cross_validation_failure#1]
great idea , great code
but may you share link to paper pls

**Comment by Sandy4321** [comment]
is it this paper
https://arxiv.org/abs/1706.07581
Cross-validation failure: small sample sizes lead to large error bars
Gaël Varoquaux (PARIETAL)

**Comment by GaelVaroquaux** [comment]
> is it this paper https://arxiv.org/abs/1706.07581 Cross-validation failure: small sample sizes lead to large error bars Gaël Varoquaux (PARIETAL)

Yes

**Comment by Sandy4321** [comment]
what is about tabular data

**Comment by GaelVaroquaux** [comment]
> what is about tabular data

Nothing in to paper is specific to neuroimaging.

**Comment by Sandy4321** [comment]
by the way 
this code 
https://gist.github.com/GaelVaroquaux/ead9898bd3c973c40429
GaelVaroquaux/mutual_info.py
is too complicated for very beginner in topic
can you help find link to some intro?

**Comment by Sandy4321** [comment]
regarding to
Figure A2: Splitting the data twice
do you now material about splitting data to test and train should be done wise way as well
similar to https://github.com/darya-chyzhyk/confound_prediction
just random split is not good enough
since many test sets can be very similar 
so big distance between test sets is needed

**Comment by Sandy4321** [comment]
there are some discussion like
https://stats.stackexchange.com/questions/97676/kozachenko-leonenko-entropy-estimation

but simple clear example need why   nearest neighbor needed

**Comment by Sandy4321** [comment]
I found 
https://github.com/paulbrodersen/entropy_estimators
from

https://stackoverflow.com/questions/43265770/entropy-python-implementation

but I need to estimate mutual info between categorical values
to find similar features
to use in https://scikit-learn.org/stable/auto_examples/bicluster/plot_spectral_coclustering.html#sphx-glr-auto-examples-bicluster-plot-spectral-coclustering-py

bicluster it using the Spectral Co-Clustering algorithm
in this link
https://www.researchgate.net/post/How_do_I_compute_the_Mutual_Information_MI_between_2_or_more_features_in_Python_when_the_data_are_not_necessarily_discrete

recommended to use
https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.mutual_info_classif.html

Estimate mutual information for a discrete target variable
may you share what python simple code may be used?

**Comment by Sandy4321** [comment]
is it good
https://github.com/jundongl/scikit-feature/blob/master/skfeature/utility/entropy_estimators.py
??
